# Hauptfarben
PRIMARY = "#2596be"
SECONDARY = "#2A9D8F"
ACCENT = "#E76F51"

# Statusfarben
SUCCESS = "#2E7D32"
WARNING = "#F4A261"
DANGER = "#C62828"

# Neutrale Farben
TEXT = "#263238"
MUTED = "#6B7280"
BORDER = "#E5E7EB"
SURFACE_MUTED = "#F1F5F4"
SIDEBAR_BG = "#FAFBFC"
CHIP_BG = "#EAF6FB"
CHIP_TEXT = PRIMARY
CHIP_BORDER = "#B9DDEA"

# Hintergruende
CARD_BG = "#F5FAFC"
PAGE_BG = "#FAFBFC"

# Diagrammfarben
COLOR_LOANS = PRIMARY
COLOR_APP = ACCENT
COLOR_RETURNS = SECONDARY
COLOR_VISITS = SECONDARY
COLOR_USAGE = SECONDARY
COLOR_EFFICIENCY = "#6C7A89"
COLOR_HOLIDAY = "#DDF6E8"
COLOR_COMPARE_A = PRIMARY
COLOR_COMPARE_B = ACCENT
COLOR_PREVIOUS = MUTED
COLOR_NEUTRAL = "#94A3B8"
COLOR_PLACEHOLDER_BG = SURFACE_MUTED
COLOR_PLACEHOLDER_TEXT = MUTED
COLOR_WEEKDAYS = [
    PRIMARY,
    ACCENT,
    SECONDARY,
    WARNING,
    COLOR_NEUTRAL,
    "#7C8FA3",
    "#B06A8A",
]

GENDER_COLORS = {
    "Weiblich": ACCENT,
    "Maennlich": PRIMARY,
    "Männlich": PRIMARY,
    "Andere": COLOR_NEUTRAL,
    "Unbekannt": BORDER,
}

BESTAND_STATUS_COLORS = {
    "🟢 behalten": SUCCESS,
    "🟡 prüfen": WARNING,
    "🔴 Bereinigung prüfen": DANGER,
}
